version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    environment:
        - VITE_API_URL=http://localhost:8080
    depends_on:
      - server
    networks:
      - tkify-net

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - CORS_ORIGINS=http://localhost:3000
      - MONGO_URI=mongodb://mongo:27017/tkify
      - PORT=8080
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=secret
      - ACCESS_TOKEN_EXPIRES=1h
      - REFRESH_TOKEN_SECRET=secret  
      - REFRESH_TOKEN_EXPIRES=30d
      - CLOUDINARY_CLOUD_NAME=YOUR_CLOUD_NAME
      - CLOUDINARY_API_KEY=YOUR_API_KEY
      - CLOUDINARY_API_SECRET=YOUR_API_SECRET
    depends_on:
      - mongo
    networks:
      - tkify-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tkify-net

networks:
  tkify-net:
    driver: bridge  
    
volumes:
  mongo-data: